/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.HeadlessException;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import Controller.PassaAlta.FiltrosPassaAlta;

/**
 *
 * @author Firmiano
 */
public class MainView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainView.class.getName());

    /**
     * Creates new form MainView
     */
    private BufferedImage imagemAtual;
    private BufferedImage imagemOriginal;// guarda a imagem que será exibida
    private JPanel painelImagem;

    public MainView() {
        initComponents();
        painelImagem = new JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                if (imagemAtual != null) {
                    g.drawImage(imagemAtual, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };

        painelImagem.setLayout(new java.awt.CardLayout());

        JScrollPane scroll = new JScrollPane(painelImagem);

        // Remove qualquer componente dentro do JFMainJpanel
        JFMainJpanel.removeAll();

        // Adiciona o scroll com o painel no JFMainJpanel
        JFMainJpanel.setLayout(new java.awt.BorderLayout());
        JFMainJpanel.add(scroll, java.awt.BorderLayout.CENTER);

        // Atualiza o layout para aplicar as mudanças
        JFMainJpanel.revalidate();
        JFMainJpanel.repaint();

        histogramaPanel = new JFHistograma();
        JFPainelHistograma.removeAll();
        JFPainelHistograma.setLayout(new java.awt.BorderLayout());
        JFPainelHistograma.add(histogramaPanel, java.awt.BorderLayout.CENTER);
        JFPainelHistograma.revalidate();
        JFPainelHistograma.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JFMainJpanel = new javax.swing.JPanel();
        JFPainelHistograma = new javax.swing.JPanel();
        JHistogramaLabel1 = new javax.swing.JLabel();
        JFDesfazerButton = new java.awt.Button();
        jMenuBar1 = new javax.swing.JMenuBar();
        JFMenuImagem = new javax.swing.JMenu();
        JFCarregarImagemMenuItem = new javax.swing.JMenuItem();
        JFSalvarImagemMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        JMenuItemFiltroPassaBaixa = new javax.swing.JMenuItem();
        JFMenuItemLaplaciano = new javax.swing.JMenuItem();
        JFMenuItemHighBoost = new javax.swing.JMenuItem();
        JFMenuItemPrewitt = new javax.swing.JMenuItem();
        JFMenuItemSobbel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDI - Sergiao\n");
        setPreferredSize(new java.awt.Dimension(1280, 720));

        JFMainJpanel.setPreferredSize(new java.awt.Dimension(512, 512));

        javax.swing.GroupLayout JFMainJpanelLayout = new javax.swing.GroupLayout(JFMainJpanel);
        JFMainJpanel.setLayout(JFMainJpanelLayout);
        JFMainJpanelLayout.setHorizontalGroup(
            JFMainJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );
        JFMainJpanelLayout.setVerticalGroup(
            JFMainJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        JFPainelHistograma.setPreferredSize(new java.awt.Dimension(750, 100));

        javax.swing.GroupLayout JFPainelHistogramaLayout = new javax.swing.GroupLayout(JFPainelHistograma);
        JFPainelHistograma.setLayout(JFPainelHistogramaLayout);
        JFPainelHistogramaLayout.setHorizontalGroup(
            JFPainelHistogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        JFPainelHistogramaLayout.setVerticalGroup(
            JFPainelHistogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JHistogramaLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        JHistogramaLabel1.setText("Histograma da Imagem");

        JFDesfazerButton.setActionCommand("Desfazer");
        JFDesfazerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JFDesfazerButton.setLabel("Desfazer");
        JFDesfazerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFDesfazerButtonActionPerformed(evt);
            }
        });
        JFDesfazerButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JFDesfazerButtonKeyPressed(evt);
            }
        });

        JFMenuImagem.setText("Imagem");

        JFCarregarImagemMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JFCarregarImagemMenuItem.setText("Carregar imagem");
        JFCarregarImagemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFCarregarImagemMenuItemActionPerformed(evt);
            }
        });
        JFMenuImagem.add(JFCarregarImagemMenuItem);

        JFSalvarImagemMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JFSalvarImagemMenuItem.setText("Salvar Imagem");
        JFSalvarImagemMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFSalvarImagemMenuItemActionPerformed(evt);
            }
        });
        JFMenuImagem.add(JFSalvarImagemMenuItem);

        jMenuBar1.add(JFMenuImagem);

        jMenu2.setText("Filtros");

        JMenuItemFiltroPassaBaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMenuItemFiltroPassaBaixa.setText("Passa Baixa");
        JMenuItemFiltroPassaBaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemFiltroPassaBaixaActionPerformed(evt);
            }
        });
        jMenu2.add(JMenuItemFiltroPassaBaixa);

        JFMenuItemLaplaciano.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JFMenuItemLaplaciano.setText("Laplaciano");
        JFMenuItemLaplaciano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFMenuItemLaplacianoActionPerformed(evt);
            }
        });
        jMenu2.add(JFMenuItemLaplaciano);

        JFMenuItemHighBoost.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JFMenuItemHighBoost.setText("High Boost");
        JFMenuItemHighBoost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFMenuItemHighBoostActionPerformed(evt);
            }
        });
        jMenu2.add(JFMenuItemHighBoost);

        JFMenuItemPrewitt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JFMenuItemPrewitt.setText("Operador de Prewitt");
        JFMenuItemPrewitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFMenuItemPrewittActionPerformed(evt);
            }
        });
        jMenu2.add(JFMenuItemPrewitt);

        JFMenuItemSobbel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JFMenuItemSobbel.setText("Operador de Sobel");
        JFMenuItemSobbel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFMenuItemSobbelActionPerformed(evt);
            }
        });
        jMenu2.add(JFMenuItemSobbel);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JFMainJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JFPainelHistograma, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JHistogramaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 552, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JFDesfazerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(JFMainJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JFDesfazerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JHistogramaLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JFPainelHistograma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JFCarregarImagemMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFCarregarImagemMenuItemActionPerformed
        JFileChooser chooser = new JFileChooser();
        int resultado = chooser.showOpenDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File arquivoSelecionado = chooser.getSelectedFile();
            try {
                BufferedImage img = ImageIO.read(arquivoSelecionado);

                // Atualiza a imagem atual
                this.imagemAtual = img;
                this.imagemOriginal = img;
                
                setImagemAtual(img);
                // Redesenha o painel
                painelImagem.repaint();
                histogramaPanel.calcularHistograma(imagemAtual);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Erro ao abrir a imagem!");
            }
        }
    }//GEN-LAST:event_JFCarregarImagemMenuItemActionPerformed

    private void JFSalvarImagemMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFSalvarImagemMenuItemActionPerformed
        if (imagemAtual == null) {
            JOptionPane.showMessageDialog(this, "Nenhuma imagem carregada para salvar!");
            return;
        }
        JFileChooser chooser = new JFileChooser();
        int resultado = chooser.showSaveDialog(this);

        if (resultado == JFileChooser.APPROVE_OPTION) {
            File arquivoSalvar = chooser.getSelectedFile();
            String caminho = arquivoSalvar.getAbsolutePath();

            // Para garantir a extensão .bmp ou .png
            if (!caminho.toLowerCase().endsWith(".bmp") && !caminho.toLowerCase().endsWith(".png") && !caminho.toLowerCase().endsWith(".jpg")) {
                caminho += ".bmp";
                arquivoSalvar = new File(caminho);
            }

            try {
                ImageIO.write(imagemAtual, "bmp", arquivoSalvar); // Salva como BMP
                JOptionPane.showMessageDialog(this, "Imagem salva com sucesso!");
            } catch (HeadlessException | IOException e) {
                JOptionPane.showMessageDialog(this, "Erro ao salvar imagem!");
            }
        }
    }//GEN-LAST:event_JFSalvarImagemMenuItemActionPerformed

    private void JMenuItemFiltroPassaBaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemFiltroPassaBaixaActionPerformed
        JFPainelFiltroPassaBaixa painelPassaBaixa = new JFPainelFiltroPassaBaixa(this);
        painelPassaBaixa.setVisible(true);
    }//GEN-LAST:event_JMenuItemFiltroPassaBaixaActionPerformed

    private void JFDesfazerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFDesfazerButtonActionPerformed
        this.imagemAtual = this.imagemOriginal;
        setImagemAtual(imagemAtual);
    }//GEN-LAST:event_JFDesfazerButtonActionPerformed

    private void JFMenuItemLaplacianoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFMenuItemLaplacianoActionPerformed
        imagemAtual = FiltrosPassaAlta.aplicarFiltroLaplacianoCinza(imagemAtual);
        setImagemAtual(imagemAtual);
    }//GEN-LAST:event_JFMenuItemLaplacianoActionPerformed

    private void JFMenuItemHighBoostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFMenuItemHighBoostActionPerformed
        imagemAtual = FiltrosPassaAlta.aplicarFiltroHighBoost(imagemAtual, 1);
        setImagemAtual(imagemAtual);
    }//GEN-LAST:event_JFMenuItemHighBoostActionPerformed

    private void JFMenuItemPrewittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFMenuItemPrewittActionPerformed
       imagemAtual = FiltrosPassaAlta.aplicarFiltroPrewitt(imagemOriginal);
        setImagemAtual(imagemAtual);
    }//GEN-LAST:event_JFMenuItemPrewittActionPerformed

    private void JFDesfazerButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JFDesfazerButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JFDesfazerButtonKeyPressed

    private void JFMenuItemSobbelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFMenuItemSobbelActionPerformed
        imagemAtual = FiltrosPassaAlta.aplicarFiltroSobel(imagemOriginal);
        setImagemAtual(imagemAtual);
    }//GEN-LAST:event_JFMenuItemSobbelActionPerformed

    public BufferedImage getImagemAtual() {
        return imagemAtual;
    }

    public void setImagemAtual(BufferedImage imagem) {
        imagemAtual = imagem;
        painelImagem = new JPanel() {
            @Override
            protected void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                if (imagemAtual != null) {
                    g.drawImage(imagemAtual, 0, 0, getWidth(), getHeight(), this);
                }
            }
        };
        JFMainJpanel.add(painelImagem, java.awt.BorderLayout.CENTER);
        JFMainJpanel.repaint();
        histogramaPanel.calcularHistograma(imagemAtual);
        JFPainelHistograma.repaint();
    }

    public void repaintPainelImagem() {
        painelImagem.repaint();
    }

    public void atualizarHistograma() {
        histogramaPanel.calcularHistograma(imagemAtual);
        JFPainelHistograma.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainView().setVisible(true));
    }

    private final JFHistograma histogramaPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JFCarregarImagemMenuItem;
    private java.awt.Button JFDesfazerButton;
    private javax.swing.JPanel JFMainJpanel;
    private javax.swing.JMenu JFMenuImagem;
    private javax.swing.JMenuItem JFMenuItemHighBoost;
    private javax.swing.JMenuItem JFMenuItemLaplaciano;
    private javax.swing.JMenuItem JFMenuItemPrewitt;
    private javax.swing.JMenuItem JFMenuItemSobbel;
    private javax.swing.JPanel JFPainelHistograma;
    private javax.swing.JMenuItem JFSalvarImagemMenuItem;
    private javax.swing.JLabel JHistogramaLabel1;
    private javax.swing.JMenuItem JMenuItemFiltroPassaBaixa;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
